/*
###############################################################
#  Generated by:      Cadence Encounter 14.27-s035_1
#  OS:                Linux x86_64(Host ID s2424.it.kth.se)
#  Generated on:      Tue Aug  2 11:42:41 2016
#  Design:            vin_spc
#  Command:           saveNetlist vin_spc_fe.v
###############################################################
*/
module vin_spc (
	Cfg_in, 
	Clk, 
	Resetn, 
	EnLF, 
	EnMF, 
	EnHF, 
	DN, 
	DP, 
	EnRdeg, 
	EnRdegHF, 
	CcompSel, 
	CapSel, 
	F, 
	IQ, 
	GS, 
	CE, 
	NS, 
	GD, 
	FS, 
	RE);
   input Cfg_in;
   input Clk;
   input Resetn;
   output EnLF;
   output EnMF;
   output EnHF;
   output [1:0] DN;
   output [2:0] DP;
   output EnRdeg;
   output [1:0] EnRdegHF;
   output [1:0] CcompSel;
   output [3:0] CapSel;
   output [3:0] F;
   output IQ;
   output [3:0] GS;
   output CE;
   output NS;
   output [2:0] GD;
   output FS;
   output RE;

   // Internal wires
   wire [5:0] count;
   wire [32:0] out;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED19;
   wire UNCONNECTED20;
   wire UNCONNECTED21;
   wire UNCONNECTED22;
   wire UNCONNECTED23;
   wire UNCONNECTED24;
   wire UNCONNECTED25;
   wire UNCONNECTED26;
   wire UNCONNECTED27;
   wire UNCONNECTED28;
   wire UNCONNECTED29;
   wire UNCONNECTED30;
   wire UNCONNECTED31;
   wire UNCONNECTED32;
   wire UNCONNECTED33;
   wire UNCONNECTED34;
   wire UNCONNECTED35;
   wire UNCONNECTED36;
   wire UNCONNECTED37;
   wire UNCONNECTED38;
   wire UNCONNECTED39;
   wire UNCONNECTED40;
   wire UNCONNECTED41;
   wire UNCONNECTED42;
   wire UNCONNECTED43;
   wire UNCONNECTED44;
   wire UNCONNECTED45;
   wire UNCONNECTED46;
   wire UNCONNECTED47;
   wire UNCONNECTED48;
   wire UNCONNECTED49;
   wire UNCONNECTED50;
   wire UNCONNECTED51;
   wire UNCONNECTED52;
   wire UNCONNECTED53;
   wire UNCONNECTED54;
   wire UNCONNECTED55;
   wire UNCONNECTED56;
   wire UNCONNECTED57;
   wire UNCONNECTED58;
   wire UNCONNECTED59;
   wire UNCONNECTED60;
   wire UNCONNECTED61;
   wire UNCONNECTED62;
   wire UNCONNECTED63;
   wire UNCONNECTED64;
   wire UNCONNECTED65;
   wire UNCONNECTED66;
   wire UNCONNECTED67;
   wire UNCONNECTED68;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_46;
   wire n_47;
   wire n_51;

   XOR2X1_HV g131 (.Q(n_8),
	.B(n_5),
	.A(count[5]));
   XOR2X1_HV g142 (.Q(n_3),
	.B(n_47),
	.A(count[2]));
   DFCX1_HV \out_reg[0]  (.RN(Resetn),
	.QN(UNCONNECTED1),
	.Q(out[0]),
	.D(out[1]),
	.CP(Clk));
   DFCX1_HV \out_reg[1]  (.RN(Resetn),
	.QN(UNCONNECTED3),
	.Q(out[1]),
	.D(out[2]),
	.CP(Clk));
   DFCX1_HV \out_reg[2]  (.RN(Resetn),
	.QN(UNCONNECTED5),
	.Q(out[2]),
	.D(out[3]),
	.CP(Clk));
   DFCX1_HV \out_reg[3]  (.RN(Resetn),
	.QN(UNCONNECTED7),
	.Q(out[3]),
	.D(out[4]),
	.CP(Clk));
   DFCX1_HV \out_reg[4]  (.RN(Resetn),
	.QN(UNCONNECTED9),
	.Q(out[4]),
	.D(out[5]),
	.CP(Clk));
   DFCX1_HV \out_reg[5]  (.RN(Resetn),
	.QN(UNCONNECTED11),
	.Q(out[5]),
	.D(out[6]),
	.CP(Clk));
   DFCX1_HV \out_reg[6]  (.RN(Resetn),
	.QN(UNCONNECTED13),
	.Q(out[6]),
	.D(out[7]),
	.CP(Clk));
   DFCX1_HV \out_reg[7]  (.RN(Resetn),
	.QN(UNCONNECTED15),
	.Q(out[7]),
	.D(out[8]),
	.CP(Clk));
   DFCX1_HV \out_reg[8]  (.RN(Resetn),
	.QN(UNCONNECTED17),
	.Q(out[8]),
	.D(out[9]),
	.CP(Clk));
   DFCX1_HV \out_reg[9]  (.RN(Resetn),
	.QN(UNCONNECTED19),
	.Q(out[9]),
	.D(out[10]),
	.CP(Clk));
   DFCX1_HV \out_reg[10]  (.RN(Resetn),
	.QN(UNCONNECTED21),
	.Q(out[10]),
	.D(out[11]),
	.CP(Clk));
   DFCX1_HV \out_reg[11]  (.RN(Resetn),
	.QN(UNCONNECTED23),
	.Q(out[11]),
	.D(out[12]),
	.CP(Clk));
   DFCX1_HV \out_reg[12]  (.RN(Resetn),
	.QN(UNCONNECTED25),
	.Q(out[12]),
	.D(out[13]),
	.CP(Clk));
   DFCX1_HV \out_reg[13]  (.RN(Resetn),
	.QN(UNCONNECTED27),
	.Q(out[13]),
	.D(out[14]),
	.CP(Clk));
   DFCX1_HV \out_reg[14]  (.RN(Resetn),
	.QN(UNCONNECTED29),
	.Q(out[14]),
	.D(out[15]),
	.CP(Clk));
   DFCX1_HV \out_reg[15]  (.RN(Resetn),
	.QN(UNCONNECTED31),
	.Q(out[15]),
	.D(out[16]),
	.CP(Clk));
   DFCX1_HV \out_reg[16]  (.RN(Resetn),
	.QN(UNCONNECTED33),
	.Q(out[16]),
	.D(out[17]),
	.CP(Clk));
   DFCX1_HV \out_reg[17]  (.RN(Resetn),
	.QN(UNCONNECTED35),
	.Q(out[17]),
	.D(out[18]),
	.CP(Clk));
   DFCX1_HV \out_reg[18]  (.RN(Resetn),
	.QN(UNCONNECTED37),
	.Q(out[18]),
	.D(out[19]),
	.CP(Clk));
   DFCX1_HV \out_reg[19]  (.RN(Resetn),
	.QN(UNCONNECTED39),
	.Q(out[19]),
	.D(out[20]),
	.CP(Clk));
   DFCX1_HV \out_reg[20]  (.RN(Resetn),
	.QN(UNCONNECTED41),
	.Q(out[20]),
	.D(out[21]),
	.CP(Clk));
   DFCX1_HV \out_reg[21]  (.RN(Resetn),
	.QN(UNCONNECTED43),
	.Q(out[21]),
	.D(out[22]),
	.CP(Clk));
   DFCX1_HV \out_reg[22]  (.RN(Resetn),
	.QN(UNCONNECTED45),
	.Q(out[22]),
	.D(out[23]),
	.CP(Clk));
   DFCX1_HV \out_reg[23]  (.RN(Resetn),
	.QN(UNCONNECTED47),
	.Q(out[23]),
	.D(out[24]),
	.CP(Clk));
   DFCX1_HV \out_reg[24]  (.RN(Resetn),
	.QN(UNCONNECTED49),
	.Q(out[24]),
	.D(out[25]),
	.CP(Clk));
   DFCX1_HV \out_reg[25]  (.RN(Resetn),
	.QN(UNCONNECTED51),
	.Q(out[25]),
	.D(out[26]),
	.CP(Clk));
   DFCX1_HV \out_reg[26]  (.RN(Resetn),
	.QN(UNCONNECTED53),
	.Q(out[26]),
	.D(out[27]),
	.CP(Clk));
   DFCX1_HV \out_reg[27]  (.RN(Resetn),
	.QN(UNCONNECTED55),
	.Q(out[27]),
	.D(out[28]),
	.CP(Clk));
   DFCX1_HV \out_reg[28]  (.RN(Resetn),
	.QN(UNCONNECTED57),
	.Q(out[28]),
	.D(out[29]),
	.CP(Clk));
   DFCX1_HV \out_reg[29]  (.RN(Resetn),
	.QN(UNCONNECTED61),
	.Q(out[29]),
	.D(out[30]),
	.CP(Clk));
   DFCX1_HV \out_reg[30]  (.RN(Resetn),
	.QN(UNCONNECTED62),
	.Q(out[30]),
	.D(out[31]),
	.CP(Clk));
   DFCX1_HV \out_reg[31]  (.RN(Resetn),
	.QN(UNCONNECTED63),
	.Q(out[31]),
	.D(out[32]),
	.CP(Clk));
   DFCX1_HV \out_reg[32]  (.RN(Resetn),
	.QN(UNCONNECTED64),
	.Q(out[32]),
	.D(Cfg_in),
	.CP(Clk));
   DFCX1_HV \count_reg[4]  (.RN(Resetn),
	.QN(UNCONNECTED66),
	.Q(count[4]),
	.D(n_7),
	.CP(Clk));
   DFCX1_HV \count_reg[3]  (.RN(Resetn),
	.QN(UNCONNECTED67),
	.Q(count[3]),
	.D(n_6),
	.CP(Clk));
   DFCX1_HV \count_reg[2]  (.RN(Resetn),
	.QN(n_51),
	.Q(count[2]),
	.D(n_3),
	.CP(Clk));
   DFCX1_HV \count_reg[1]  (.RN(Resetn),
	.QN(UNCONNECTED68),
	.Q(count[1]),
	.D(n_4),
	.CP(Clk));
   XNOR2X2_HV g140 (.Q(n_6),
	.B(count[3]),
	.A(n_2));
   XNOR2X2_HV g141 (.Q(n_4),
	.B(count[1]),
	.A(count[0]));
   DFCX6_HV RE_reg (.RN(Resetn),
	.QN(UNCONNECTED),
	.Q(RE),
	.D(out[0]),
	.CP(n_10));
   DFCX6_HV FS_reg (.RN(Resetn),
	.QN(UNCONNECTED0),
	.Q(FS),
	.D(out[1]),
	.CP(n_10));
   DFCX6_HV \GD_reg[0]  (.RN(Resetn),
	.QN(UNCONNECTED2),
	.Q(GD[0]),
	.D(out[2]),
	.CP(n_10));
   DFCX6_HV \GD_reg[1]  (.RN(Resetn),
	.QN(UNCONNECTED4),
	.Q(GD[1]),
	.D(out[3]),
	.CP(n_10));
   DFCX6_HV \GD_reg[2]  (.RN(Resetn),
	.QN(UNCONNECTED6),
	.Q(GD[2]),
	.D(out[4]),
	.CP(n_10));
   DFCX6_HV NS_reg (.RN(Resetn),
	.QN(UNCONNECTED8),
	.Q(NS),
	.D(out[5]),
	.CP(n_10));
   DFCX6_HV CE_reg (.RN(Resetn),
	.QN(UNCONNECTED10),
	.Q(CE),
	.D(out[6]),
	.CP(n_10));
   DFCX6_HV \GS_reg[0]  (.RN(Resetn),
	.QN(UNCONNECTED12),
	.Q(GS[0]),
	.D(out[7]),
	.CP(n_10));
   DFCX6_HV \GS_reg[1]  (.RN(Resetn),
	.QN(UNCONNECTED14),
	.Q(GS[1]),
	.D(out[8]),
	.CP(n_10));
   DFCX6_HV \GS_reg[2]  (.RN(Resetn),
	.QN(UNCONNECTED16),
	.Q(GS[2]),
	.D(out[9]),
	.CP(n_10));
   DFCX6_HV \GS_reg[3]  (.RN(Resetn),
	.QN(UNCONNECTED18),
	.Q(GS[3]),
	.D(out[10]),
	.CP(n_10));
   DFCX6_HV IQ_reg (.RN(Resetn),
	.QN(UNCONNECTED20),
	.Q(IQ),
	.D(out[11]),
	.CP(n_10));
   DFCX6_HV \F_reg[0]  (.RN(Resetn),
	.QN(UNCONNECTED22),
	.Q(F[0]),
	.D(out[12]),
	.CP(n_10));
   DFCX6_HV \F_reg[1]  (.RN(Resetn),
	.QN(UNCONNECTED24),
	.Q(F[1]),
	.D(out[13]),
	.CP(n_10));
   DFCX6_HV \F_reg[2]  (.RN(Resetn),
	.QN(UNCONNECTED26),
	.Q(F[2]),
	.D(out[14]),
	.CP(n_10));
   DFCX6_HV \F_reg[3]  (.RN(Resetn),
	.QN(UNCONNECTED28),
	.Q(F[3]),
	.D(out[15]),
	.CP(n_10));
   DFCX6_HV \CapSel_reg[0]  (.RN(Resetn),
	.QN(UNCONNECTED30),
	.Q(CapSel[0]),
	.D(out[16]),
	.CP(n_10));
   DFCX6_HV \CapSel_reg[1]  (.RN(Resetn),
	.QN(UNCONNECTED32),
	.Q(CapSel[1]),
	.D(out[17]),
	.CP(n_10));
   DFCX6_HV \CapSel_reg[2]  (.RN(Resetn),
	.QN(UNCONNECTED34),
	.Q(CapSel[2]),
	.D(out[18]),
	.CP(n_10));
   DFCX6_HV \CapSel_reg[3]  (.RN(Resetn),
	.QN(UNCONNECTED36),
	.Q(CapSel[3]),
	.D(out[19]),
	.CP(n_10));
   DFCX6_HV \CcompSel_reg[0]  (.RN(Resetn),
	.QN(UNCONNECTED38),
	.Q(CcompSel[0]),
	.D(out[20]),
	.CP(n_10));
   DFCX6_HV \CcompSel_reg[1]  (.RN(Resetn),
	.QN(UNCONNECTED40),
	.Q(CcompSel[1]),
	.D(out[21]),
	.CP(n_10));
   DFCX6_HV \EnRdegHF_reg[0]  (.RN(Resetn),
	.QN(UNCONNECTED42),
	.Q(EnRdegHF[0]),
	.D(out[22]),
	.CP(n_10));
   DFCX6_HV \EnRdegHF_reg[1]  (.RN(Resetn),
	.QN(UNCONNECTED44),
	.Q(EnRdegHF[1]),
	.D(out[23]),
	.CP(n_10));
   DFCX6_HV EnRdeg_reg (.RN(Resetn),
	.QN(UNCONNECTED46),
	.Q(EnRdeg),
	.D(out[24]),
	.CP(n_10));
   DFCX6_HV \DP_reg[0]  (.RN(Resetn),
	.QN(UNCONNECTED48),
	.Q(DP[0]),
	.D(out[25]),
	.CP(n_10));
   DFCX6_HV \DP_reg[1]  (.RN(Resetn),
	.QN(UNCONNECTED50),
	.Q(DP[1]),
	.D(out[26]),
	.CP(n_10));
   DFCX6_HV \DP_reg[2]  (.RN(Resetn),
	.QN(UNCONNECTED52),
	.Q(DP[2]),
	.D(out[27]),
	.CP(n_10));
   DFCX6_HV \DN_reg[0]  (.RN(Resetn),
	.QN(UNCONNECTED54),
	.Q(DN[0]),
	.D(out[28]),
	.CP(n_10));
   DFCX6_HV \DN_reg[1]  (.RN(Resetn),
	.QN(UNCONNECTED56),
	.Q(DN[1]),
	.D(out[29]),
	.CP(n_10));
   DFCX6_HV EnMF_reg (.RN(Resetn),
	.QN(UNCONNECTED58),
	.Q(EnMF),
	.D(out[31]),
	.CP(n_10));
   DFCX6_HV EnHF_reg (.RN(Resetn),
	.QN(UNCONNECTED59),
	.Q(EnHF),
	.D(out[30]),
	.CP(n_10));
   DFCX6_HV EnLF_reg (.RN(Resetn),
	.QN(UNCONNECTED60),
	.Q(EnLF),
	.D(out[32]),
	.CP(n_10));
   DFPX3_HV \count_reg[5]  (.SN(Resetn),
	.QN(UNCONNECTED65),
	.Q(count[5]),
	.D(n_8),
	.CP(Clk));
   DFPX3_HV \count_reg[0]  (.SN(Resetn),
	.QN(n_0),
	.Q(count[0]),
	.D(n_0),
	.CP(Clk));
   NAND2XL_HV g143 (.Q(n_2),
	.B(n_51),
	.A(n_47));
   NAND2XL_HV g144 (.Q(n_1),
	.B(n_47),
	.A(n_46));
   NAND3X1_HV g137 (.Q(n_9),
	.C(n_11),
	.B(n_47),
	.A(n_46));
   NOR2XL_HV g42 (.Q(n_46),
	.B(count[3]),
	.A(count[2]));
   NOR2XL_HV g44 (.Q(n_11),
	.B(count[4]),
	.A(count[5]));
   NOR2XL_HV g135 (.Q(n_10),
	.B(n_9),
	.A(Clk));
   NOR2XL_HV g139 (.Q(n_47),
	.B(count[0]),
	.A(count[1]));
   NOR2XL_HV g138 (.Q(n_5),
	.B(count[4]),
	.A(n_1));
   AO21X3_HV g136 (.Q(n_7),
	.B1(n_5),
	.A2(count[4]),
	.A1(n_1));
endmodule

