
// Generated by Cadence Encounter(R) RTL Compiler RC14.23 - v14.20-s027_1

// Verification Directory fv/FreqDiv 

module FreqDiv(Fin, Fsel, Resetn, Fout, F_PFD);
  input Fin, Resetn;
  input [3:0] Fsel;
  output Fout, F_PFD;
  wire Fin, Resetn;
  wire [3:0] Fsel;
  wire Fout, F_PFD;
  wire [14:0] divider;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46;
  MUX2X6_HV g442(.A (n_46), .B (n_45), .S (Fsel[3]), .Q (Fout));
  OAI211X3_HV g443(.A1 (n_38), .A2 (n_30), .B1 (n_43), .C1 (n_42), .Q
       (n_46));
  OAI221X3_HV g444(.A1 (n_39), .A2 (n_33), .B1 (n_40), .B2 (n_32), .C1
       (n_44), .Q (n_45));
  OA22X3_HV g445(.A1 (n_41), .A2 (n_34), .B1 (n_37), .B2 (n_30), .Q
       (n_44));
  OA22X3_HV g446(.A1 (n_35), .A2 (n_33), .B1 (n_36), .B2 (n_34), .Q
       (n_43));
  OAI221X3_HV g447(.A1 (Fin), .A2 (Fsel[0]), .B1 (divider[0]), .B2
       (n_28), .C1 (n_31), .Q (n_42));
  IMUX2XL_HV g448(.A (divider[11]), .B (divider[12]), .S (Fsel[0]), .Q
       (n_41));
  IMUX2XL_HV g449(.A (divider[7]), .B (divider[8]), .S (Fsel[0]), .Q
       (n_40));
  IMUX2XL_HV g450(.A (divider[9]), .B (divider[13]), .S (Fsel[2]), .Q
       (n_39));
  IMUX2XL_HV g451(.A (divider[2]), .B (divider[6]), .S (Fsel[2]), .Q
       (n_38));
  IMUX2XL_HV g452(.A (divider[10]), .B (divider[14]), .S (Fsel[2]), .Q
       (n_37));
  IMUX2XL_HV g453(.A (F_PFD), .B (divider[3]), .S (n_28), .Q (n_36));
  IMUX2XL_HV g454(.A (divider[1]), .B (divider[5]), .S (Fsel[2]), .Q
       (n_35));
  OR2X2_HV g455(.A (n_29), .B (Fsel[1]), .Q (n_34));
  NAND2XL_HV g456(.A (n_28), .B (Fsel[1]), .Q (n_33));
  INVXL_HV g457(.A (n_31), .Q (n_32));
  NOR2XL_HV g458(.A (Fsel[1]), .B (Fsel[2]), .Q (n_31));
  NAND2XL_HV g459(.A (Fsel[0]), .B (Fsel[1]), .Q (n_30));
  INVXL_HV g460(.A (Fsel[2]), .Q (n_29));
  INVXL_HV g461(.A (Fsel[0]), .Q (n_28));
  DFCX1_HV \divider_reg[14] (.RN (Resetn), .CP (Fin), .D (n_27), .Q
       (divider[14]), .QN (UNCONNECTED));
  XOR2X1_HV g266(.A (divider[14]), .B (n_25), .Q (n_27));
  DFCX1_HV \divider_reg[13] (.RN (Resetn), .CP (Fin), .D (n_26), .Q
       (divider[13]), .QN (UNCONNECTED0));
  HAX3_HV g268(.A (n_23), .B (divider[13]), .CO (n_25), .SUM (n_26));
  DFCX1_HV \divider_reg[12] (.RN (Resetn), .CP (Fin), .D (n_24), .Q
       (divider[12]), .QN (UNCONNECTED1));
  HAX3_HV g270(.A (n_21), .B (divider[12]), .CO (n_23), .SUM (n_24));
  DFCX1_HV \divider_reg[11] (.RN (Resetn), .CP (Fin), .D (n_22), .Q
       (divider[11]), .QN (UNCONNECTED2));
  HAX3_HV g272(.A (n_19), .B (divider[11]), .CO (n_21), .SUM (n_22));
  DFCX1_HV \divider_reg[10] (.RN (Resetn), .CP (Fin), .D (n_20), .Q
       (divider[10]), .QN (UNCONNECTED3));
  HAX3_HV g274(.A (n_17), .B (divider[10]), .CO (n_19), .SUM (n_20));
  DFCX1_HV \divider_reg[9] (.RN (Resetn), .CP (Fin), .D (n_18), .Q
       (divider[9]), .QN (UNCONNECTED4));
  HAX3_HV g276(.A (n_15), .B (divider[9]), .CO (n_17), .SUM (n_18));
  DFCX1_HV \divider_reg[8] (.RN (Resetn), .CP (Fin), .D (n_16), .Q
       (divider[8]), .QN (UNCONNECTED5));
  HAX3_HV g278(.A (n_13), .B (divider[8]), .CO (n_15), .SUM (n_16));
  DFCX1_HV \divider_reg[7] (.RN (Resetn), .CP (Fin), .D (n_14), .Q
       (divider[7]), .QN (UNCONNECTED6));
  HAX3_HV g280(.A (n_11), .B (divider[7]), .CO (n_13), .SUM (n_14));
  DFCX1_HV \divider_reg[6] (.RN (Resetn), .CP (Fin), .D (n_12), .Q
       (divider[6]), .QN (UNCONNECTED7));
  HAX3_HV g282(.A (n_9), .B (divider[6]), .CO (n_11), .SUM (n_12));
  DFCX1_HV \divider_reg[5] (.RN (Resetn), .CP (Fin), .D (n_10), .Q
       (divider[5]), .QN (UNCONNECTED8));
  HAX3_HV g284(.A (n_7), .B (divider[5]), .CO (n_9), .SUM (n_10));
  DFCX6_HV \divider_reg[4] (.RN (Resetn), .CP (Fin), .D (n_8), .Q
       (F_PFD), .QN (UNCONNECTED9));
  HAX3_HV g286(.A (n_5), .B (F_PFD), .CO (n_7), .SUM (n_8));
  DFCX1_HV \divider_reg[3] (.RN (Resetn), .CP (Fin), .D (n_6), .Q
       (divider[3]), .QN (UNCONNECTED10));
  HAX3_HV g288(.A (n_3), .B (divider[3]), .CO (n_5), .SUM (n_6));
  DFCX1_HV \divider_reg[2] (.RN (Resetn), .CP (Fin), .D (n_4), .Q
       (divider[2]), .QN (UNCONNECTED11));
  HAX3_HV g290(.A (n_1), .B (divider[2]), .CO (n_3), .SUM (n_4));
  DFCX1_HV \divider_reg[1] (.RN (Resetn), .CP (Fin), .D (n_2), .Q
       (divider[1]), .QN (UNCONNECTED12));
  HAX3_HV g292(.A (divider[0]), .B (divider[1]), .CO (n_1), .SUM (n_2));
  DFCX1_HV \divider_reg[0] (.RN (Resetn), .CP (Fin), .D (n_0), .Q
       (divider[0]), .QN (n_0));
endmodule

