
// Generated by Cadence Encounter(R) RTL Compiler RC14.25 - v14.20-s046_1

// Verification Directory fv/cur_dec 

module shift_left_vlog_unsigned(A, SH, Z);
  input A;
  input [3:0] SH;
  output [15:0] Z;
  wire A;
  wire [3:0] SH;
  wire [15:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_11;
  wire n_12, n_13, n_15;
  INVXL g64(.A (SH[3]), .Q (n_6));
  NOR2X3 g162(.A (n_3), .B (n_11), .Q (Z[15]));
  NOR2X3 g163(.A (n_3), .B (n_12), .Q (Z[13]));
  NOR2X3 g164(.A (n_5), .B (n_13), .Q (Z[10]));
  NOR2X3 g165(.A (n_4), .B (n_12), .Q (Z[4]));
  NOR2X3 g166(.A (n_2), .B (n_13), .Q (Z[3]));
  NOR2X3 g167(.A (n_3), .B (n_15), .Q (Z[9]));
  NOR2X3 g168(.A (n_4), .B (n_13), .Q (Z[2]));
  NOR2X3 g169(.A (n_2), .B (n_15), .Q (Z[1]));
  NOR2X3 g170(.A (n_5), .B (n_15), .Q (Z[8]));
  NOR2X3 g171(.A (n_4), .B (n_15), .Q (Z[0]));
  NOR2X3 g172(.A (n_2), .B (n_11), .Q (Z[7]));
  NOR2X3 g173(.A (n_5), .B (n_11), .Q (Z[14]));
  NOR2X3 g174(.A (n_5), .B (n_12), .Q (Z[12]));
  NOR2X3 g175(.A (n_4), .B (n_11), .Q (Z[6]));
  NOR2X3 g176(.A (n_3), .B (n_13), .Q (Z[11]));
  NOR2X3 g177(.A (n_2), .B (n_12), .Q (Z[5]));
  NAND2XL g178(.A (n_1), .B (SH[3]), .Q (n_5));
  NAND2XL g179(.A (n_1), .B (n_6), .Q (n_4));
  NAND2XL g180(.A (SH[0]), .B (SH[3]), .Q (n_3));
  NAND2XL g181(.A (SH[0]), .B (n_6), .Q (n_2));
  INVXL g182(.A (SH[0]), .Q (n_1));
  NAND2XL g67(.A (n_0), .B (SH[2]), .Q (n_12));
  OR2X3 g68(.A (SH[2]), .B (n_0), .Q (n_13));
  NAND2XL g69(.A (SH[2]), .B (SH[1]), .Q (n_11));
  OR2X3 g70(.A (SH[1]), .B (SH[2]), .Q (n_15));
  INVXL g71(.A (SH[1]), .Q (n_0));
endmodule

module cur_dec(in, out);
  input [3:0] in;
  output [15:0] out;
  wire [3:0] in;
  wire [15:0] out;
  wire logic_1_1_net;
  shift_left_vlog_unsigned sll_18_12(.A (logic_1_1_net), .SH (in), .Z
       (out));
  LOGIC1 tie_1_cell(.Q (logic_1_1_net));
endmodule

