
// Generated by Cadence Encounter(R) RTL Compiler RC14.25 - v14.20-s046_1

// Verification Directory fv/fet_dec 

module shift_left_vlog_unsigned(A, SH, Z);
  input A;
  input [4:0] SH;
  output [31:0] Z;
  wire A;
  wire [4:0] SH;
  wire [31:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_15, n_17;
  wire n_29, n_31, n_34, n_36;
  INVXL g123(.A (SH[3]), .Q (n_11));
  NOR2X3 g316(.A (n_8), .B (n_12), .Q (Z[31]));
  NOR2X3 g317(.A (n_8), .B (n_13), .Q (Z[29]));
  NOR2X3 g318(.A (n_10), .B (n_15), .Q (Z[26]));
  NOR2X3 g319(.A (n_9), .B (n_13), .Q (Z[20]));
  NOR2X3 g320(.A (n_9), .B (n_31), .Q (Z[4]));
  NOR2X3 g321(.A (n_7), .B (n_34), .Q (Z[3]));
  NOR2X3 g322(.A (n_7), .B (n_15), .Q (Z[19]));
  NOR2X3 g323(.A (n_9), .B (n_34), .Q (Z[2]));
  NOR2X3 g324(.A (n_7), .B (n_36), .Q (Z[1]));
  NOR2X3 g325(.A (n_8), .B (n_17), .Q (Z[25]));
  NOR2X3 g326(.A (n_9), .B (n_15), .Q (Z[18]));
  NOR2X3 g327(.A (n_9), .B (n_36), .Q (Z[0]));
  NOR2X3 g328(.A (n_7), .B (n_17), .Q (Z[17]));
  NOR2X3 g329(.A (n_10), .B (n_17), .Q (Z[24]));
  NOR2X3 g330(.A (n_9), .B (n_17), .Q (Z[16]));
  NOR2X3 g331(.A (n_8), .B (n_29), .Q (Z[15]));
  NOR2X3 g332(.A (n_7), .B (n_12), .Q (Z[23]));
  NOR2X3 g333(.A (n_10), .B (n_29), .Q (Z[14]));
  NOR2X3 g334(.A (n_8), .B (n_31), .Q (Z[13]));
  NOR2X3 g335(.A (n_10), .B (n_12), .Q (Z[30]));
  NOR2X3 g336(.A (n_10), .B (n_13), .Q (Z[28]));
  NOR2X3 g337(.A (n_10), .B (n_31), .Q (Z[12]));
  NOR2X3 g338(.A (n_8), .B (n_34), .Q (Z[11]));
  NOR2X3 g339(.A (n_9), .B (n_12), .Q (Z[22]));
  NOR2X3 g340(.A (n_10), .B (n_34), .Q (Z[10]));
  NOR2X3 g341(.A (n_8), .B (n_36), .Q (Z[9]));
  NOR2X3 g342(.A (n_8), .B (n_15), .Q (Z[27]));
  NOR2X3 g343(.A (n_10), .B (n_36), .Q (Z[8]));
  NOR2X3 g344(.A (n_7), .B (n_29), .Q (Z[7]));
  NOR2X3 g345(.A (n_7), .B (n_13), .Q (Z[21]));
  NOR2X3 g346(.A (n_9), .B (n_29), .Q (Z[6]));
  NOR2X3 g347(.A (n_7), .B (n_31), .Q (Z[5]));
  NAND2X3 g348(.A (n_6), .B (SH[3]), .Q (n_10));
  NAND2X3 g349(.A (n_6), .B (n_11), .Q (n_9));
  NAND2X3 g350(.A (SH[0]), .B (SH[3]), .Q (n_8));
  NAND2X3 g351(.A (SH[0]), .B (n_11), .Q (n_7));
  INVXL g352(.A (SH[0]), .Q (n_6));
  NAND2XL g191(.A (n_2), .B (SH[4]), .Q (n_12));
  NAND2XL g192(.A (n_3), .B (SH[4]), .Q (n_17));
  NAND2XL g193(.A (n_3), .B (n_1), .Q (n_36));
  NAND2XL g194(.A (n_2), .B (n_1), .Q (n_29));
  NAND2XL g195(.A (n_4), .B (n_1), .Q (n_34));
  NAND2XL g196(.A (n_4), .B (SH[4]), .Q (n_15));
  NAND2XL g197(.A (n_5), .B (SH[4]), .Q (n_13));
  NAND2XL g198(.A (n_5), .B (n_1), .Q (n_31));
  NOR2XL g199(.A (n_0), .B (SH[1]), .Q (n_5));
  AND2X3 g200(.A (SH[1]), .B (n_0), .Q (n_4));
  NOR2XL g201(.A (SH[1]), .B (SH[2]), .Q (n_3));
  AND2X3 g202(.A (SH[2]), .B (SH[1]), .Q (n_2));
  INVXL g203(.A (SH[4]), .Q (n_1));
  INVXL g204(.A (SH[2]), .Q (n_0));
endmodule

module fet_dec(in, out);
  input [4:0] in;
  output [31:0] out;
  wire [4:0] in;
  wire [31:0] out;
  wire logic_1_1_net;
  shift_left_vlog_unsigned sll_18_12(.A (logic_1_1_net), .SH (in), .Z
       (out));
  LOGIC1 tie_1_cell(.Q (logic_1_1_net));
endmodule

