
// Generated by Cadence Encounter(R) RTL Compiler RC14.25 - v14.20-s046_1

// Verification Directory fv/nnspc 

module nnspc(Cfg_in, Clk, Resetn, NSEL, DAC, RE);
  input Cfg_in, Clk, Resetn;
  output [4:0] NSEL;
  output [3:0] DAC;
  output RE;
  wire Cfg_in, Clk, Resetn;
  wire [4:0] NSEL;
  wire [3:0] DAC;
  wire RE;
  wire [4:0] count;
  wire [9:0] out;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_12, n_13;
  NOR2XL g33(.A (count[2]), .B (count[1]), .Q (n_13));
  NOR2XL g34(.A (count[4]), .B (count[3]), .Q (n_12));
  DFCX3 RE_reg(.RN (Resetn), .CP (n_9), .D (out[0]), .Q (RE), .QN
       (UNCONNECTED));
  DFCX3 \DAC_reg[0] (.RN (Resetn), .CP (n_9), .D (out[1]), .Q (DAC[0]),
       .QN (UNCONNECTED0));
  DFCX1 \out_reg[0] (.RN (Resetn), .CP (Clk), .D (out[1]), .Q (out[0]),
       .QN (UNCONNECTED1));
  DFCX3 \DAC_reg[1] (.RN (Resetn), .CP (n_9), .D (out[2]), .Q (DAC[1]),
       .QN (UNCONNECTED2));
  DFCX1 \out_reg[1] (.RN (Resetn), .CP (Clk), .D (out[2]), .Q (out[1]),
       .QN (UNCONNECTED3));
  DFCX3 \DAC_reg[2] (.RN (Resetn), .CP (n_9), .D (out[3]), .Q (DAC[2]),
       .QN (UNCONNECTED4));
  DFCX1 \out_reg[2] (.RN (Resetn), .CP (Clk), .D (out[3]), .Q (out[2]),
       .QN (UNCONNECTED5));
  DFCX3 \DAC_reg[3] (.RN (Resetn), .CP (n_9), .D (out[4]), .Q (DAC[3]),
       .QN (UNCONNECTED6));
  DFCX1 \out_reg[3] (.RN (Resetn), .CP (Clk), .D (out[4]), .Q (out[3]),
       .QN (UNCONNECTED7));
  DFCX3 \NSEL_reg[0] (.RN (Resetn), .CP (n_9), .D (out[5]), .Q
       (NSEL[0]), .QN (UNCONNECTED8));
  DFCX1 \out_reg[4] (.RN (Resetn), .CP (Clk), .D (out[5]), .Q (out[4]),
       .QN (UNCONNECTED9));
  DFCX3 \NSEL_reg[1] (.RN (Resetn), .CP (n_9), .D (out[6]), .Q
       (NSEL[1]), .QN (UNCONNECTED10));
  DFCX1 \out_reg[5] (.RN (Resetn), .CP (Clk), .D (out[6]), .Q (out[5]),
       .QN (UNCONNECTED11));
  DFCX3 \NSEL_reg[3] (.RN (Resetn), .CP (n_9), .D (out[8]), .Q
       (NSEL[3]), .QN (UNCONNECTED12));
  DFCX3 \NSEL_reg[2] (.RN (Resetn), .CP (n_9), .D (out[7]), .Q
       (NSEL[2]), .QN (UNCONNECTED13));
  DFCX3 \NSEL_reg[4] (.RN (Resetn), .CP (n_9), .D (out[9]), .Q
       (NSEL[4]), .QN (UNCONNECTED14));
  DFCX1 \out_reg[6] (.RN (Resetn), .CP (Clk), .D (out[7]), .Q (out[6]),
       .QN (UNCONNECTED15));
  DFCX1 \out_reg[7] (.RN (Resetn), .CP (Clk), .D (out[8]), .Q (out[7]),
       .QN (UNCONNECTED16));
  NOR2XL g81(.A (Clk), .B (n_8), .Q (n_9));
  DFCX1 \out_reg[8] (.RN (Resetn), .CP (Clk), .D (out[9]), .Q (out[8]),
       .QN (UNCONNECTED17));
  NAND3X1 g83(.A (n_12), .B (n_13), .C (n_10), .Q (n_8));
  DFCX1 \out_reg[9] (.RN (Resetn), .CP (Clk), .D (Cfg_in), .Q (out[9]),
       .QN (UNCONNECTED18));
  DFCX1 \count_reg[4] (.RN (Resetn), .CP (Clk), .D (n_7), .Q
       (count[4]), .QN (UNCONNECTED19));
  XOR2X1 g136(.A (count[4]), .B (n_5), .Q (n_7));
  DFPX3 \count_reg[3] (.SN (Resetn), .CP (Clk), .D (n_6), .Q
       (count[3]), .QN (UNCONNECTED20));
  XOR2X1 g138(.A (count[3]), .B (n_2), .Q (n_6));
  DFCX1 \count_reg[2] (.RN (Resetn), .CP (Clk), .D (n_3), .Q
       (count[2]), .QN (UNCONNECTED21));
  NOR2XL g140(.A (n_4), .B (count[3]), .Q (n_5));
  INVXL g141(.A (n_2), .Q (n_4));
  DFPX3 \count_reg[1] (.SN (Resetn), .CP (Clk), .D (n_1), .Q
       (count[1]), .QN (UNCONNECTED22));
  AO21X3 g143(.A1 (n_0), .A2 (count[2]), .B1 (n_2), .Q (n_3));
  NOR2XL g144(.A (n_0), .B (count[2]), .Q (n_2));
  XOR2X1 g145(.A (count[1]), .B (n_10), .Q (n_1));
  DFCX1 \count_reg[0] (.RN (Resetn), .CP (Clk), .D (n_10), .Q
       (count[0]), .QN (n_10));
  OR2X3 g147(.A (count[1]), .B (count[0]), .Q (n_0));
endmodule

