
// Generated by Cadence Encounter(R) RTL Compiler RC14.25 - v14.20-s046_1

// Verification Directory fv/vin_spc 

module vin_spc(Cfg_in, Clk, Resetn, EnLF, EnMF, EnHF, DN, DP, EnRdeg,
     EnRdegHF, CcompSel, CapSel, F, IQ, GS, CE, NS, GD, FS, RE);
  input Cfg_in, Clk, Resetn;
  output EnLF, EnMF, EnHF, EnRdeg, IQ, CE, NS, FS, RE;
  output [1:0] DN, EnRdegHF, CcompSel;
  output [2:0] DP, GD;
  output [3:0] CapSel, F, GS;
  wire Cfg_in, Clk, Resetn;
  wire EnLF, EnMF, EnHF, EnRdeg, IQ, CE, NS, FS, RE;
  wire [1:0] DN, EnRdegHF, CcompSel;
  wire [2:0] DP, GD;
  wire [3:0] CapSel, F, GS;
  wire [5:0] count;
  wire [32:0] out;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62;
  wire UNCONNECTED63, UNCONNECTED64, UNCONNECTED65, UNCONNECTED66,
       UNCONNECTED67, UNCONNECTED68, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_46, n_47, n_51;
  NOR2XL_HV g42(.A (count[2]), .B (count[3]), .Q (n_46));
  NOR2XL_HV g44(.A (count[5]), .B (count[4]), .Q (n_11));
  DFCX6_HV RE_reg(.RN (Resetn), .CP (n_10), .D (out[0]), .Q (RE), .QN
       (UNCONNECTED));
  DFCX6_HV FS_reg(.RN (Resetn), .CP (n_10), .D (out[1]), .Q (FS), .QN
       (UNCONNECTED0));
  DFCX1_HV \out_reg[0] (.RN (Resetn), .CP (Clk), .D (out[1]), .Q
       (out[0]), .QN (UNCONNECTED1));
  DFCX6_HV \GD_reg[0] (.RN (Resetn), .CP (n_10), .D (out[2]), .Q
       (GD[0]), .QN (UNCONNECTED2));
  DFCX1_HV \out_reg[1] (.RN (Resetn), .CP (Clk), .D (out[2]), .Q
       (out[1]), .QN (UNCONNECTED3));
  DFCX6_HV \GD_reg[1] (.RN (Resetn), .CP (n_10), .D (out[3]), .Q
       (GD[1]), .QN (UNCONNECTED4));
  DFCX1_HV \out_reg[2] (.RN (Resetn), .CP (Clk), .D (out[3]), .Q
       (out[2]), .QN (UNCONNECTED5));
  DFCX6_HV \GD_reg[2] (.RN (Resetn), .CP (n_10), .D (out[4]), .Q
       (GD[2]), .QN (UNCONNECTED6));
  DFCX1_HV \out_reg[3] (.RN (Resetn), .CP (Clk), .D (out[4]), .Q
       (out[3]), .QN (UNCONNECTED7));
  DFCX6_HV NS_reg(.RN (Resetn), .CP (n_10), .D (out[5]), .Q (NS), .QN
       (UNCONNECTED8));
  DFCX1_HV \out_reg[4] (.RN (Resetn), .CP (Clk), .D (out[5]), .Q
       (out[4]), .QN (UNCONNECTED9));
  DFCX6_HV CE_reg(.RN (Resetn), .CP (n_10), .D (out[6]), .Q (CE), .QN
       (UNCONNECTED10));
  DFCX1_HV \out_reg[5] (.RN (Resetn), .CP (Clk), .D (out[6]), .Q
       (out[5]), .QN (UNCONNECTED11));
  DFCX6_HV \GS_reg[0] (.RN (Resetn), .CP (n_10), .D (out[7]), .Q
       (GS[0]), .QN (UNCONNECTED12));
  DFCX1_HV \out_reg[6] (.RN (Resetn), .CP (Clk), .D (out[7]), .Q
       (out[6]), .QN (UNCONNECTED13));
  DFCX6_HV \GS_reg[1] (.RN (Resetn), .CP (n_10), .D (out[8]), .Q
       (GS[1]), .QN (UNCONNECTED14));
  DFCX1_HV \out_reg[7] (.RN (Resetn), .CP (Clk), .D (out[8]), .Q
       (out[7]), .QN (UNCONNECTED15));
  DFCX6_HV \GS_reg[2] (.RN (Resetn), .CP (n_10), .D (out[9]), .Q
       (GS[2]), .QN (UNCONNECTED16));
  DFCX1_HV \out_reg[8] (.RN (Resetn), .CP (Clk), .D (out[9]), .Q
       (out[8]), .QN (UNCONNECTED17));
  DFCX6_HV \GS_reg[3] (.RN (Resetn), .CP (n_10), .D (out[10]), .Q
       (GS[3]), .QN (UNCONNECTED18));
  DFCX1_HV \out_reg[9] (.RN (Resetn), .CP (Clk), .D (out[10]), .Q
       (out[9]), .QN (UNCONNECTED19));
  DFCX6_HV IQ_reg(.RN (Resetn), .CP (n_10), .D (out[11]), .Q (IQ), .QN
       (UNCONNECTED20));
  DFCX1_HV \out_reg[10] (.RN (Resetn), .CP (Clk), .D (out[11]), .Q
       (out[10]), .QN (UNCONNECTED21));
  DFCX6_HV \F_reg[0] (.RN (Resetn), .CP (n_10), .D (out[12]), .Q
       (F[0]), .QN (UNCONNECTED22));
  DFCX1_HV \out_reg[11] (.RN (Resetn), .CP (Clk), .D (out[12]), .Q
       (out[11]), .QN (UNCONNECTED23));
  DFCX6_HV \F_reg[1] (.RN (Resetn), .CP (n_10), .D (out[13]), .Q
       (F[1]), .QN (UNCONNECTED24));
  DFCX1_HV \out_reg[12] (.RN (Resetn), .CP (Clk), .D (out[13]), .Q
       (out[12]), .QN (UNCONNECTED25));
  DFCX6_HV \F_reg[2] (.RN (Resetn), .CP (n_10), .D (out[14]), .Q
       (F[2]), .QN (UNCONNECTED26));
  DFCX1_HV \out_reg[13] (.RN (Resetn), .CP (Clk), .D (out[14]), .Q
       (out[13]), .QN (UNCONNECTED27));
  DFCX6_HV \F_reg[3] (.RN (Resetn), .CP (n_10), .D (out[15]), .Q
       (F[3]), .QN (UNCONNECTED28));
  DFCX1_HV \out_reg[14] (.RN (Resetn), .CP (Clk), .D (out[15]), .Q
       (out[14]), .QN (UNCONNECTED29));
  DFCX6_HV \CapSel_reg[0] (.RN (Resetn), .CP (n_10), .D (out[16]), .Q
       (CapSel[0]), .QN (UNCONNECTED30));
  DFCX1_HV \out_reg[15] (.RN (Resetn), .CP (Clk), .D (out[16]), .Q
       (out[15]), .QN (UNCONNECTED31));
  DFCX6_HV \CapSel_reg[1] (.RN (Resetn), .CP (n_10), .D (out[17]), .Q
       (CapSel[1]), .QN (UNCONNECTED32));
  DFCX1_HV \out_reg[16] (.RN (Resetn), .CP (Clk), .D (out[17]), .Q
       (out[16]), .QN (UNCONNECTED33));
  DFCX6_HV \CapSel_reg[2] (.RN (Resetn), .CP (n_10), .D (out[18]), .Q
       (CapSel[2]), .QN (UNCONNECTED34));
  DFCX1_HV \out_reg[17] (.RN (Resetn), .CP (Clk), .D (out[18]), .Q
       (out[17]), .QN (UNCONNECTED35));
  DFCX6_HV \CapSel_reg[3] (.RN (Resetn), .CP (n_10), .D (out[19]), .Q
       (CapSel[3]), .QN (UNCONNECTED36));
  DFCX1_HV \out_reg[18] (.RN (Resetn), .CP (Clk), .D (out[19]), .Q
       (out[18]), .QN (UNCONNECTED37));
  DFCX6_HV \CcompSel_reg[0] (.RN (Resetn), .CP (n_10), .D (out[20]), .Q
       (CcompSel[0]), .QN (UNCONNECTED38));
  DFCX1_HV \out_reg[19] (.RN (Resetn), .CP (Clk), .D (out[20]), .Q
       (out[19]), .QN (UNCONNECTED39));
  DFCX6_HV \CcompSel_reg[1] (.RN (Resetn), .CP (n_10), .D (out[21]), .Q
       (CcompSel[1]), .QN (UNCONNECTED40));
  DFCX1_HV \out_reg[20] (.RN (Resetn), .CP (Clk), .D (out[21]), .Q
       (out[20]), .QN (UNCONNECTED41));
  DFCX6_HV \EnRdegHF_reg[0] (.RN (Resetn), .CP (n_10), .D (out[22]), .Q
       (EnRdegHF[0]), .QN (UNCONNECTED42));
  DFCX1_HV \out_reg[21] (.RN (Resetn), .CP (Clk), .D (out[22]), .Q
       (out[21]), .QN (UNCONNECTED43));
  DFCX6_HV \EnRdegHF_reg[1] (.RN (Resetn), .CP (n_10), .D (out[23]), .Q
       (EnRdegHF[1]), .QN (UNCONNECTED44));
  DFCX1_HV \out_reg[22] (.RN (Resetn), .CP (Clk), .D (out[23]), .Q
       (out[22]), .QN (UNCONNECTED45));
  DFCX6_HV EnRdeg_reg(.RN (Resetn), .CP (n_10), .D (out[24]), .Q
       (EnRdeg), .QN (UNCONNECTED46));
  DFCX1_HV \out_reg[23] (.RN (Resetn), .CP (Clk), .D (out[24]), .Q
       (out[23]), .QN (UNCONNECTED47));
  DFCX6_HV \DP_reg[0] (.RN (Resetn), .CP (n_10), .D (out[25]), .Q
       (DP[0]), .QN (UNCONNECTED48));
  DFCX1_HV \out_reg[24] (.RN (Resetn), .CP (Clk), .D (out[25]), .Q
       (out[24]), .QN (UNCONNECTED49));
  DFCX6_HV \DP_reg[1] (.RN (Resetn), .CP (n_10), .D (out[26]), .Q
       (DP[1]), .QN (UNCONNECTED50));
  DFCX1_HV \out_reg[25] (.RN (Resetn), .CP (Clk), .D (out[26]), .Q
       (out[25]), .QN (UNCONNECTED51));
  DFCX6_HV \DP_reg[2] (.RN (Resetn), .CP (n_10), .D (out[27]), .Q
       (DP[2]), .QN (UNCONNECTED52));
  DFCX1_HV \out_reg[26] (.RN (Resetn), .CP (Clk), .D (out[27]), .Q
       (out[26]), .QN (UNCONNECTED53));
  DFCX6_HV \DN_reg[0] (.RN (Resetn), .CP (n_10), .D (out[28]), .Q
       (DN[0]), .QN (UNCONNECTED54));
  DFCX1_HV \out_reg[27] (.RN (Resetn), .CP (Clk), .D (out[28]), .Q
       (out[27]), .QN (UNCONNECTED55));
  DFCX6_HV \DN_reg[1] (.RN (Resetn), .CP (n_10), .D (out[29]), .Q
       (DN[1]), .QN (UNCONNECTED56));
  DFCX1_HV \out_reg[28] (.RN (Resetn), .CP (Clk), .D (out[29]), .Q
       (out[28]), .QN (UNCONNECTED57));
  DFCX6_HV EnMF_reg(.RN (Resetn), .CP (n_10), .D (out[31]), .Q (EnMF),
       .QN (UNCONNECTED58));
  DFCX6_HV EnHF_reg(.RN (Resetn), .CP (n_10), .D (out[30]), .Q (EnHF),
       .QN (UNCONNECTED59));
  DFCX6_HV EnLF_reg(.RN (Resetn), .CP (n_10), .D (out[32]), .Q (EnLF),
       .QN (UNCONNECTED60));
  DFCX1_HV \out_reg[29] (.RN (Resetn), .CP (Clk), .D (out[30]), .Q
       (out[29]), .QN (UNCONNECTED61));
  DFCX1_HV \out_reg[30] (.RN (Resetn), .CP (Clk), .D (out[31]), .Q
       (out[30]), .QN (UNCONNECTED62));
  NOR2XL_HV g135(.A (Clk), .B (n_9), .Q (n_10));
  DFCX1_HV \out_reg[31] (.RN (Resetn), .CP (Clk), .D (out[32]), .Q
       (out[31]), .QN (UNCONNECTED63));
  NAND3X1_HV g137(.A (n_46), .B (n_47), .C (n_11), .Q (n_9));
  DFCX1_HV \out_reg[32] (.RN (Resetn), .CP (Clk), .D (Cfg_in), .Q
       (out[32]), .QN (UNCONNECTED64));
  NOR2XL_HV g139(.A (count[1]), .B (count[0]), .Q (n_47));
  DFPX3_HV \count_reg[5] (.SN (Resetn), .CP (Clk), .D (n_8), .Q
       (count[5]), .QN (UNCONNECTED65));
  XOR2X1_HV g131(.A (count[5]), .B (n_5), .Q (n_8));
  DFCX1_HV \count_reg[4] (.RN (Resetn), .CP (Clk), .D (n_7), .Q
       (count[4]), .QN (UNCONNECTED66));
  DFCX1_HV \count_reg[3] (.RN (Resetn), .CP (Clk), .D (n_6), .Q
       (count[3]), .QN (UNCONNECTED67));
  DFCX1_HV \count_reg[2] (.RN (Resetn), .CP (Clk), .D (n_3), .Q
       (count[2]), .QN (n_51));
  DFCX1_HV \count_reg[1] (.RN (Resetn), .CP (Clk), .D (n_4), .Q
       (count[1]), .QN (UNCONNECTED68));
  AO21X3_HV g136(.A1 (n_1), .A2 (count[4]), .B1 (n_5), .Q (n_7));
  XNOR2X2_HV g140(.A (n_2), .B (count[3]), .Q (n_6));
  NOR2XL_HV g138(.A (n_1), .B (count[4]), .Q (n_5));
  XNOR2X2_HV g141(.A (count[0]), .B (count[1]), .Q (n_4));
  XOR2X1_HV g142(.A (count[2]), .B (n_47), .Q (n_3));
  DFPX3_HV \count_reg[0] (.SN (Resetn), .CP (Clk), .D (n_0), .Q
       (count[0]), .QN (n_0));
  NAND2XL_HV g143(.A (n_47), .B (n_51), .Q (n_2));
  NAND2XL_HV g144(.A (n_46), .B (n_47), .Q (n_1));
endmodule

