/*
###############################################################
#  Generated by:      Cadence Encounter 14.25-s034_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Sun Nov  8 19:54:47 2015
#  Design:            DacCtrl
#  Command:           saveNetlist DacCtrl_fe.v
###############################################################
*/
module DacCtrl (
	CountEnable, 
	Clk, 
	Resetn, 
	StepNum, 
	P, 
	IP, 
	IN, 
	QP, 
	QN);
   input CountEnable;
   input Clk;
   input Resetn;
   input StepNum;
   output [16:0] P;
   output IP;
   output IN;
   output QP;
   output QN;

   // Internal wires
   wire [4:0] count;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_27;
   wire n_28;
   wire n_30;
   wire n_31;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_42;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_51;
   wire n_54;
   wire n_55;
   wire n_58;

   NOR2X3_HV g1155 (.Q(P[13]),
	.B(n_54),
	.A(n_58));
   NOR2X3_HV g1153 (.Q(P[5]),
	.B(count[4]),
	.A(n_58));
   NOR2X3_HV g1154 (.Q(P[3]),
	.B(count[4]),
	.A(n_55));
   NOR2X3_HV g1156 (.Q(P[11]),
	.B(n_54),
	.A(n_55));
   NOR2X3_HV g1148 (.Q(P[9]),
	.B(n_54),
	.A(n_51));
   NOR2X3_HV g1147 (.Q(P[1]),
	.B(count[4]),
	.A(n_51));
   NOR2X3_HV g1151 (.Q(P[7]),
	.B(count[4]),
	.A(n_42));
   NOR2X3_HV g1152 (.Q(P[15]),
	.B(n_54),
	.A(n_42));
   DFCX3_HV QP_reg (.RN(Resetn),
	.QN(QN),
	.Q(QP),
	.D(IP),
	.CP(n_2));
   HAX3_HV g1162 (.SUM(n_22),
	.CO(n_34),
	.B(count[3]),
	.A(n_21));
   HAX3_HV g1182 (.SUM(n_16),
	.CO(n_30),
	.B(count[3]),
	.A(n_6));
   IMUX2XL_HV g1194 (.S(StepNum),
	.Q(n_2),
	.B(n_6),
	.A(n_44));
   AND2X3_HV g1176 (.Q(n_36),
	.B(count[2]),
	.A(n_31));
   AND2X3_HV g1185 (.Q(n_23),
	.B(n_17),
	.A(n_18));
   AND2X3_HV g1186 (.Q(n_31),
	.B(count[0]),
	.A(n_18));
   INVXL_HV g1195 (.Q(n_8),
	.A(n_7));
   INVXL_HV g1181 (.Q(n_14),
	.A(n_9));
   INVXL_HV g1198 (.Q(n_37),
	.A(n_11));
   INVXL_HV g1201 (.Q(n_38),
	.A(n_1));
   INVXL_HV g1205 (.Q(n_6),
	.A(count[2]));
   INVXL_HV g1210 (.Q(n_0),
	.A(StepNum));
   OAI31X6_HV g1171 (.Q(P[0]),
	.B1(CountEnable),
	.A3(count[0]),
	.A2(count[1]),
	.A1(n_4));
   DFCX1_HV \count_reg[3]  (.RN(Resetn),
	.QN(n_44),
	.Q(count[3]),
	.D(n_22),
	.CP(Clk));
   DFCX1_HV \count_reg[1]  (.RN(Resetn),
	.QN(n_5),
	.Q(count[1]),
	.D(n_10),
	.CP(Clk));
   DFCX1_HV \count_reg[0]  (.RN(Resetn),
	.QN(n_17),
	.Q(count[0]),
	.D(n_17),
	.CP(Clk));
   AOI32X3_HV g1168 (.Q(n_58),
	.B2(n_44),
	.B1(n_36),
	.A3(n_37),
	.A2(n_38),
	.A1(n_30));
   AOI32X3_HV g1167 (.Q(n_55),
	.B2(count[3]),
	.B1(n_36),
	.A3(n_37),
	.A2(n_38),
	.A1(n_35));
   AOI32X3_HV g1161 (.Q(n_42),
	.B2(n_30),
	.B1(n_31),
	.A3(n_37),
	.A2(n_44),
	.A1(n_21));
   OR2X3_HV g1174 (.Q(n_39),
	.B(n_13),
	.A(n_14));
   AOI22X3_HV g1149 (.Q(n_51),
	.B2(n_37),
	.B1(n_34),
	.A2(n_31),
	.A1(n_35));
   XNOR2X2_HV g1196 (.Q(n_7),
	.B(count[2]),
	.A(n_5));
   AOI21X3_HV g1190 (.Q(n_4),
	.B1(n_35),
	.A2(StepNum),
	.A1(n_6));
   NAND2XL_HV g1175 (.Q(n_46),
	.B(n_30),
	.A(n_23));
   NAND2XL_HV g1177 (.Q(n_40),
	.B(count[2]),
	.A(n_23));
   NAND2XL_HV g1178 (.Q(n_45),
	.B(count[2]),
	.A(n_12));
   NAND2XL_HV g1199 (.Q(n_11),
	.B(CountEnable),
	.A(n_0));
   NAND2XL_HV g1202 (.Q(n_1),
	.B(count[0]),
	.A(count[1]));
   NAND2XL_HV g1200 (.Q(n_13),
	.B(StepNum),
	.A(CountEnable));
   OAI22X3_HV g1163 (.Q(P[8]),
	.B2(count[3]),
	.B1(n_45),
	.A2(count[4]),
	.A1(n_46));
   OAI22X3_HV g1165 (.Q(P[4]),
	.B2(count[3]),
	.B1(n_39),
	.A2(count[4]),
	.A1(n_40));
   OAI22X3_HV g1164 (.Q(P[16]),
	.B2(n_44),
	.B1(n_45),
	.A2(n_54),
	.A1(n_46));
   OAI22X3_HV g1166 (.Q(P[12]),
	.B2(n_44),
	.B1(n_39),
	.A2(n_54),
	.A1(n_40));
   OAI22X3_HV g1158 (.Q(P[2]),
	.B2(count[3]),
	.B1(n_24),
	.A2(count[4]),
	.A1(n_25));
   OAI22X3_HV g1157 (.Q(P[10]),
	.B2(n_44),
	.B1(n_24),
	.A2(n_54),
	.A1(n_25));
   MUX2X3_HV g1193 (.S(StepNum),
	.Q(IN),
	.B(count[3]),
	.A(count[4]));
   NAND3X3_HV g1170 (.Q(n_25),
	.C(n_37),
	.B(n_9),
	.A(n_16));
   DFCSX2_HV \count_reg[4]  (.SI(n_54),
	.SE(n_34),
	.RN(Resetn),
	.QN(UNCONNECTED),
	.Q(count[4]),
	.D(count[4]),
	.CP(Clk));
   DFCSX2_HV \count_reg[2]  (.SI(n_6),
	.SE(n_38),
	.RN(Resetn),
	.QN(UNCONNECTED0),
	.Q(count[2]),
	.D(count[2]),
	.CP(Clk));
   NOR2XL_HV g1188 (.Q(n_18),
	.B(n_11),
	.A(count[1]));
   NOR2XL_HV g1189 (.Q(n_21),
	.B(n_6),
	.A(n_1));
   NOR2XL_HV g1204 (.Q(n_9),
	.B(count[0]),
	.A(n_5));
   NOR2XL_HV g1203 (.Q(n_35),
	.B(count[3]),
	.A(count[2]));
   OR3X3_HV g1179 (.Q(n_24),
	.C(n_13),
	.B(n_17),
	.A(n_7));
   AO22X3_HV g1160 (.Q(P[6]),
	.B2(n_44),
	.B1(n_27),
	.A2(n_54),
	.A1(n_28));
   AO22X3_HV g1159 (.Q(P[14]),
	.B2(count[3]),
	.B1(n_27),
	.A2(count[4]),
	.A1(n_28));
   INVX3_HV g1192 (.Q(IP),
	.A(IN));
   INVX3_HV g1208 (.Q(n_54),
	.A(count[4]));
   NOR3X3_HV g1180 (.Q(n_27),
	.C(n_13),
	.B(n_17),
	.A(n_8));
   NOR3X3_HV g1172 (.Q(n_28),
	.C(n_11),
	.B(n_14),
	.A(n_16));
   NOR3X3_HV g1187 (.Q(n_12),
	.C(n_13),
	.B(count[0]),
	.A(count[1]));
   AO21X3_HV g1191 (.Q(n_10),
	.B1(n_9),
	.A2(count[0]),
	.A1(n_5));
endmodule

